### Site info:
title: "lmh3 Page"
motto: "博学之，审问之，慎思之，明辨之，笃行之"
author: "MenghuaLu"
email: "lmh31415@gmail.com"
description: "MenghuaLu Page"
keywords: ""
baseurl: ""
url: ""
locale: en_US

### Personal info and site tools info:
twitter_username: "MenghuaLu"  
github_username:  "lmh3"
favicon:     "/images/favicon.ico"
aboutme: "Hi, this is MenghuaLu. I made this blog to write something. Please enjoy it."
aboutme_photo: "/images/aboutme.png" 

### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "cn" # blog sidebar language set, only include: English (en), Chinese (cn), Japanese (jp), Polish (pl), Korean (kr) and Russian (ru) 

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Categories: "Categories"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
      Google_search: "Site Search"
      Home: "Home"
      About: "About"
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Categories: "分类目录"    
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "
      Google_search: "站内搜索"
      Home: "首页"
      About: "关于"


### Build settings
markdown: kramdown
#highlighter: pygments
kramdown:
        input: GFM
        syntax_highlighter: rouge
gems: [jekyll-paginate]
paginate: 5
excerpt_separator: <!-- more -->
